Sistema_Gestión_Estancia_Ganadera/Obligatorio/Obligatorio/WebApp/Controllers/EmpleadoController.cs
using Microsoft.AspNetCore.Mvc;
using Obligatorio.Dominio;
using System;
using System.Linq.Expressions;
using static System.Collections.Specialized.BitVector32;

namespace WebApp.Controllers
{
    public class EmpleadoController : Controller
    {
        Sistema sistema = Sistema.Instance();
        public IActionResult IngresoEmpleados()
        {
            if (HttpContext.Session.GetString("rolEmpleadoLogueado") == null)
            {
                return View();
            }
            return RedirectToAction("Index", "Inicio");
        }
        [HttpPost]
        public IActionResult IngresoEmpleados(string email, string contraseña)
        {
            if (HttpContext.Session.GetString("rolEmpleadoLogueado") == null)
            {
                try
                {
                    Empleado empleadoLogueado = sistema.GetEmpleadoXEmailYContraseña(email, contraseña);
                    HttpContext.Session.SetString("rolEmpleadoLogueado", empleadoLogueado.GetType().Name);
                    HttpContext.Session.SetString("nombreEmpleadoLogueado", empleadoLogueado.Nombre);
                    HttpContext.Session.SetInt32("idEmpleadoLogueado", empleadoLogueado.Id);
                    if (empleadoLogueado is Peon)
                    {
                        return RedirectToAction("InicioPeon");
                    }
                    else
                    {
                        return RedirectToAction("InicioCapataz");
                    }
                }
                catch (Exception ex)
                {
                    ViewBag.Mensaje = ex.Message;
                }
                return View();
            }
            return RedirectToAction("Index", "Inicio");
        }

        public IActionResult Salir()
        {
            if (HttpContext.Session.GetString("rolEmpleadoLogueado") == "Peon" || HttpContext.Session.GetString("rolEmpleadoLogueado") == "Capataz")
            {
                HttpContext.Session.Clear();
            }
            return RedirectToAction("Index", "Inicio");
        }

        public IActionResult EditPeon(int id)
        {
            if (HttpContext.Session.GetString("rolEmpleadoLogueado") == "Peon")
            {
                Peon peonLogueado = (Peon)sistema.GetEmpleadoXId(id);
                return View(peonLogueado);
            }
            return RedirectToAction("Index", "Inicio");
        }
        [HttpPost]
        public IActionResult EditPeon(Peon pPeon)
        {
            if (HttpContext.Session.GetString("rolEmpleadoLogueado") == "Peon")
            {
                try
                {
                    sistema.ActualizarPeon(pPeon);
                    ViewBag.Mensaje = "Actualización con éxito";
                    return View(pPeon);
                }
                catch (Exception ex)
                {
                    ViewBag.Mensaje = ex.Message;
                }
                return View();
            }
            return RedirectToAction("Index", "Inicio");
        }

        public IActionResult RegistroPeon()
        {
            if (HttpContext.Session.GetString("rolEmpleadoLogueado") == null)
            {
                return View();
            }
            return RedirectToAction("Index", "Inicio");
        }
        [HttpPost]
        public IActionResult RegistroPeon(Peon pPeon)
        {
            if (HttpContext.Session.GetString("rolEmpleadoLogueado") == null)
            {
                try
                {
                    sistema.AltaEmpleado(pPeon);
                    ViewBag.Mensaje = "Registro realizado con éxito!";
                    return View();
                }
                catch (Exception ex)
                {
                    ViewBag.Mensaje = ex.Message;
                    return View();
                }
            }
            return RedirectToAction("Index", "Inicio");
        }

        public IActionResult InicioPeon()
        {
            if (HttpContext.Session.GetString("rolEmpleadoLogueado") == "Peon")
            {
                int? idEmpleadoLogueado = HttpContext.Session.GetInt32("idEmpleadoLogueado");
                Peon peonLogueado = (Peon)sistema.GetEmpleadoXId(idEmpleadoLogueado);
                ViewBag.NombreEmpleado = peonLogueado.Nombre;
                ViewBag.EmailEmpleado = peonLogueado.Email;
                ViewBag.ContraseñaEmpleado = peonLogueado.Contraseña;
                ViewBag.FechaIngresoEmpleado = peonLogueado.FechaIngreso.ToShortDateString();
                ViewBag.EsResidente = peonLogueado.EsResidente;
                return View();
            }
            return RedirectToAction("Index", "Inicio");
        }

        public IActionResult InicioCapataz()
        {
            if (HttpContext.Session.GetString("rolEmpleadoLogueado") == "Capataz")
            {
                int? idEmpleadoLogueado = HttpContext.Session.GetInt32("idEmpleadoLogueado");
                Capataz capatazLogueado = (Capataz)sistema.GetEmpleadoXId(idEmpleadoLogueado);
                ViewBag.NombreEmpleado = capatazLogueado.Nombre;
                ViewBag.EmailEmpleado = capatazLogueado.Email;
                ViewBag.ContraseñaEmpleado = capatazLogueado.Contraseña;
                ViewBag.FechaIngresoEmpleado = capatazLogueado.FechaIngreso.ToShortDateString();
                ViewBag.PersonasACargo = capatazLogueado.CantidadPersonasACargo;
                return View();
            }
            return RedirectToAction("Index", "Inicio");
        }
        public IActionResult EditCapataz(int id)
        {
            if (HttpContext.Session.GetString("rolEmpleadoLogueado") == "Capataz")
            {
                Capataz capatazLogueado = (Capataz)sistema.GetEmpleadoXId(id);
                return View(capatazLogueado);
            }
            return RedirectToAction("Index", "Inicio");
        }
        [HttpPost]
        public IActionResult EditCapataz(Capataz pCapataz)
        {
            if (HttpContext.Session.GetString("rolEmpleadoLogueado") == "Capataz")
            {
                try
                {
                    sistema.ActualizarCapataz(pCapataz);
                    ViewBag.Mensaje = "Actualización con éxito";
                    return View(pCapataz);
                }
                catch (Exception ex)
                {
                    ViewBag.Mensaje = ex.Message;
                    return View();
                }
            }
            return RedirectToAction("Index", "Inicio");
        }
        public IActionResult ListaPeones()
        {
            if (HttpContext.Session.GetString("rolEmpleadoLogueado") == "Capataz")
            {
                return View(sistema.GetPeones());
            }
            return RedirectToAction("Index", "Inicio");
        }
        public IActionResult DarDeBaja(int idPeon)
        {
            sistema.DarDeBajaEmpleado(idPeon);
            return RedirectToAction("ListaPeones");
        }
    }
}

Sistema_Gestión_Estancia_Ganadera/Obligatorio/Obligatorio/WebApp/Controllers/GanadoController.cs
using Microsoft.AspNetCore.Mvc;
using Obligatorio.Dominio;

namespace WebApp.Controllers
{
    public class GanadoController : Controller
    {
        Sistema sistema = Sistema.Instance();
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult RegistrarNuevoBovino()
        {
            if (HttpContext.Session.GetString("rolEmpleadoLogueado") == "Capataz")
            {
                return View();
            }

            return RedirectToAction("Index", "Inicio");
        }
        [HttpPost]
        public IActionResult RegistrarNuevoBovino(Bovino pBovino)
        {
            if (HttpContext.Session.GetString("rolEmpleadoLogueado") == "Capataz")
            {
                try
                {
                    sistema.AltaGanado(pBovino);
                    sistema.AsignarPotreroAAltaGanado(pBovino);
                    ViewBag.Mensaje = "Animal Registrado con éxito!";
                }
                catch (Exception ex)
                {
                    ViewBag.Mensaje = ex.Message;
                }
                return View();
            }
            return RedirectToAction("Index", "Inicio");
        }
        public IActionResult MostrarAnimal()
        {
            if (HttpContext.Session.GetString("rolEmpleadoLogueado") == "Capataz")
            {
                return View();
            }
            return RedirectToAction("Index", "Inicio");
        }
        [HttpPost]
        public IActionResult MostrarAnimal(string tipoAnimal, int pesoGanado)
        {
            if (HttpContext.Session.GetString("rolEmpleadoLogueado") == "Capataz")
            {
                sistema.SetGananciaPorGanado();
                TempData["pesoGanado"] = pesoGanado;
                if (tipoAnimal == "Bovino")
                {
                    return RedirectToAction("MostrarBovinos");
                }
                else
                {
                    return RedirectToAction("MostrarOvinos");
                }
            }
            return RedirectToAction("Index", "Inicio");
        }
       
        public IActionResult MostrarBovinos()
        {
            if (HttpContext.Session.GetString("rolEmpleadoLogueado") == "Capataz")
            {
                int? pesoGanado = TempData["pesoGanado"] as int?;
                return View(sistema.GetBovinosXPeso(pesoGanado));
            }
            return RedirectToAction("Index", "Inicio");
        }

        public IActionResult MostrarOvinos()
        {
            if (HttpContext.Session.GetString("rolEmpleadoLogueado") == "Capataz")
            {
                int? pesoGanado = TempData["pesoGanado"] as int?;
                return View(sistema.GetOvinosXPeso(pesoGanado));
            }
            return RedirectToAction("Index", "Inicio");
        }
    }
}

Sistema_Gestión_Estancia_Ganadera/Obligatorio/Obligatorio/WebApp/Controllers/PotreroController.cs
using Microsoft.AspNetCore.Mvc;
using Obligatorio.Dominio;

namespace WebApp.Controllers
{
    public class PotreroController : Controller
    {
        Sistema sistema = Sistema.Instance();
        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("rolEmpleadoLogueado") == "Capataz")
            {
                ViewBag.Potreros = sistema.GetPotreros();
                return View(sistema.GetGanadoAlAireLibre());
            }
            return RedirectToAction("Index", "Inicio");
        }
        [HttpPost]
        public IActionResult Index(int idPotrero, int numCaravana)
        {
            if (HttpContext.Session.GetString("rolEmpleadoLogueado") == "Capataz")
            {
                Ganado pGanado = sistema.GetGanadoXNumCaravana(numCaravana);
                Potrero potreroAMover = sistema.GetPotreroXId(idPotrero);
                ViewBag.Potreros = sistema.GetPotreros();
                try
                {
                    sistema.MoverGanadoLibreAPotrero(potreroAMover, pGanado);
                    ViewBag.Mensaje = "Animal movido con éxito";
                    return View(sistema.GetGanadoAlAireLibre());
                }
                catch (Exception ex)
                {
                    ViewBag.Mensaje = ex.Message;
                    return View();
                }
            }
            return RedirectToAction("Index", "Inicio");
        }
        public IActionResult ListaPotreros()
        {
            if (HttpContext.Session.GetString("rolEmpleadoLogueado") == "Capataz")
            {
                sistema.SetGananciaPorPotrero();
                List<Potrero> listPotreros = new List<Potrero>();
                listPotreros = sistema.GetPotreros();                
                listPotreros.Sort();
                return View(listPotreros);
            }
            return RedirectToAction("Index", "Inicio");
        }
    }
}

Sistema_Gestión_Estancia_Ganadera/Obligatorio/Obligatorio/WebApp/Controllers/TareasController.cs
using Microsoft.AspNetCore.Mvc;
using Obligatorio.Dominio;

namespace WebApp.Controllers
{
    public class TareasController : Controller
    {
        Sistema sistema = Sistema.Instance();
        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("rolEmpleadoLogueado") == "Peon")
            {
                int? idLogueado = HttpContext.Session.GetInt32("idEmpleadoLogueado");
                Peon peonLogueado = (Peon)sistema.GetEmpleadoXId(idLogueado);
                return View(sistema.GetTareasNoRealizadasXPeon(peonLogueado));
            }
            return RedirectToAction("Index", "Inicio");
        }

        public IActionResult CompletarTarea()
        {
            if (HttpContext.Session.GetString("rolEmpleadoLogueado") == "Peon")
            {
                int? idLogueado = HttpContext.Session.GetInt32("idEmpleadoLogueado");
                Peon peonLogueado = (Peon)sistema.GetEmpleadoXId(idLogueado);
                ViewBag.AsignacionTareas = sistema.GetTareasNoRealizadasXPeon(peonLogueado);
                return View();
            }
            return RedirectToAction("Index", "Inicio");
        }
        [HttpPost]
        public IActionResult CompletarTarea(int idTarea, string pComentario)
        {
            if (HttpContext.Session.GetString("rolEmpleadoLogueado") == "Peon")
            {
                int? idLogueado = HttpContext.Session.GetInt32("idEmpleadoLogueado");
                Peon peonLogueado = (Peon)sistema.GetEmpleadoXId(idLogueado);
                AsignacionTarea tareaAcompletar = sistema.GetAsignacionTareaPorPeon(idLogueado, idTarea);
                ViewBag.AsignacionTareas = sistema.GetTareasNoRealizadasXPeon(peonLogueado);
                try
                {
                    sistema.CompletarAsignacionTarea(tareaAcompletar, pComentario);
                    ViewBag.Mensaje = "Tarea Finalizada con éxito";
                    ViewBag.AsignacionTareas = sistema.GetTareasNoRealizadasXPeon(peonLogueado);
                    return View();
                }
                catch (Exception ex)
                {
                    ViewBag.Mensaje = ex.Message + " - Verifique Tarea Seleccionada - ";
                }
                return View();
            }
            return RedirectToAction("Index", "Inicio");
        }
        public IActionResult ListaTareasPeon(int idPeon)
        {
            if (HttpContext.Session.GetString("rolEmpleadoLogueado") == "Capataz")
            {
                return View(sistema.GetAsignacionTareasXIdPeon(idPeon));
            }
            return RedirectToAction("Index", "Inicio");
        }

        public IActionResult AsignarTarea(int idPeon)
        {
            if (HttpContext.Session.GetString("rolEmpleadoLogueado") == "Capataz")
            {
                TempData["idPeon"] = idPeon;
                return View();
            }
            return RedirectToAction("Index", "Inicio");
        }
        [HttpPost]
        public IActionResult AsignarTarea(Tarea pTarea)
        {
            if (HttpContext.Session.GetString("rolEmpleadoLogueado") == "Capataz")
            {
                int? idPeon = TempData["idPeon"] as int?;
                try
                {
                    sistema.AltaTarea(pTarea);
                    Peon _peon = (Peon)sistema.GetEmpleadoXId(idPeon);
                    AsignacionTarea _asignacionTarea = new AsignacionTarea(_peon, pTarea);
                    sistema.AltaAsignacionTarea(_asignacionTarea);
                    ViewBag.Mensaje = "Tarea Agregada a peón con éxito!";
                }
                catch (Exception ex)
                {
                    ViewBag.Mensaje = ex.Message;
                }
                return View();
            }
            return RedirectToAction("Index", "Inicio");
        }
    }
}

Sistema_Gestión_Estancia_Ganadera/Obligatorio/Obligatorio/WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]Nuestra Granja</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="" asp-action="">Nuestra Granja</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (Context.Session.GetString("rolEmpleadoLogueado") == null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Empleado" asp-action="IngresoEmpleados">Inicio de Sesión</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Empleado" asp-action="RegistroPeon">Registro</a>
                            </li>
                        }
                        @if (Context.Session.GetString("rolEmpleadoLogueado") == "Capataz")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Empleado" asp-action="InicioCapataz">Inicio</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Ganado" asp-action="RegistrarNuevoBovino">Registrar Bovino</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Potrero" asp-action="Index">Animal Libre a Potrero</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Empleado" asp-action="ListaPeones">Lista Peones</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Potrero" asp-action="ListaPotreros">Lista Potreros</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Ganado" asp-action="MostrarAnimal">Mostrar Animal</a>
                            </li>
                        }
                        @if (Context.Session.GetString("rolEmpleadoLogueado") == "Peon")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Empleado" asp-action="InicioPeon">Inicio</a>
                            </li>
                            <li style="text-align:center">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Vacunacion" asp-action="Index">Vacunación</a>
                            </li>
                            <li>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Tareas" asp-action="Index">Tareas</a>
                            </li>

                        }
                        @if (Context.Session.GetString("rolEmpleadoLogueado") != null)
                        {

                            <li class="nav-item ms-auto">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Empleado" asp-action="Salir">Salir</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>